service: ecs-app

provider:
  name: aws
  ecr:
    images:
      app:
        path: ./
        file: Dockerfile

plugins:
  - serverless-fargate

fargate:
  vpc:
    subnetIds:
      - subnet-1234
  tasks:
    ecs-app:
      image: app
      entryPoint: node
      command: app.js
  memory: '0.5GB'
  cpu: 256
  logGroupName: ecs-app-log-group



